### ISSUE TITLE
Strange smudges around notifications Gnome Ubuntu 18.10

### ISSUE THREAD

**Issue by JohnEdChristensen** [vinceliuice/Qogir-theme#17]
These show up around notifications.
![screenshot from 2018-10-19 19-40-50](https://user-images.githubusercontent.com/29576860/47315858-eb413d00-d602-11e8-8b05-ddb65c0ca01f.png)

**Comment by vinceliuice** [comment]
I' ll fix this

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by JohnEdChristensen** [comment]
I'm still experiencing the same problem after your fix, I completely removed and then installed the updated version.

**Comment by vinceliuice** [comment]
Forget the notification-banner, now fixed! you can try again!

**Comment by vinceliuice** [comment]
By the way you need relogin or reboot to see the changes
